### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [AlvaroMartinFernandez/formulario#1]
Bien hecho, pero necesitamos algunos ajustes:

- No es responsive
- Estilo de símbolo $ en input amount.
- En los input nombre, apellido, ciudad validar campo de entrada que pueda contener solo letras (sin números, ni caracteres especiales).
- Has intentado la validación, lo cual está bien, pero la lógica no funciona y se superpone código de js y css. Si quieres activarla, deja solo uno de ellos, y ten en cuenta que con js no podrías mostrar un .alert-success salvo que utilizaras preventDefault para evitar que se mande el formulario, ya que en caso contrario se recargará la página borrándose de la memoria el estado actual de la aplicación

**Comment by AlvaroMartinFernandez** [comment]
Buenas, no lo hice responsivo,  por que, como comenté a noelia a mi parecer no está bien propuesto el ejercicio, te indica que en una caja está el nombre y en otra el apellido por lo que si lo hago responsivo con esa estructura pondrías el nombre luego la ciudad,  después el método de pago y luego el apellido, seguí las cajas del protecto no me parecía cómodo para la experencia del usuario. Si me indicas cambio la distribuccion de las cajas, lo hago responsive y soluciono los otros problemas.

**Comment by agarzon48** [comment]
Hola, Álvaro!

Lo primero que quiero matizar (lo recordaré en clase para que sirva también a tus compañeros) es que, afortunadamente, la corrección de los proyectos de la academia no es automatizada, sino manual. Esto supone más trabajo para Noe y para mí, pero os ofrece una mayor flexibilidad.

Lo que quiero decir con esto es que no hace falta que sigáis las instrucciones al pie de la letra, ni en este ni en otros proyectos. Mientras quede reflejado que habéis dominado los conceptos de la lección (en este caso cómo trabajar con elementos HTML de formulario) nosotros estamos completamente abiertos a modificaciones, personalizaciones y, sobre todo, mejoras (como tu alert.js, que aprecio que hayas escrito).

Pese a ello, en este caso se trata solo de una cuestión de maquetación. Tú has decidido que hubiera un col-6 con los campos firstName, city y acceptedCards y otro para los campos lastName, state, postalCode y message. En realidad, si cada uno hubiera estado dentro de un "col-12 col-md-6" o algo similar (la mitad para state y postal code) le podrías haber sacado partido al grid de bootstrap (12 slots por row) para que se recolocaran automágicamente. De modo que hay estrategias para seguir el modelo de la academia (que, insisto, podéis cambiar si lo estimáis oportuno) sin que deje de ser responsive.

En resumen, dale una vuelta para reestructurarlo de un modo que consideres óptimo, pero que también sea responsive. He visto también que se pueden seleccionar varias tarjetas. La gracia era que fuera un radio para que solo se pudiera seleccionar una, alternativamente. Cambia esto también, por favor.

Si lo has hecho porque consideras mejor que se puedan seleccionar varias tarjetas, introduce los cambios necesarios para que yo pueda desmarcar la selección si me he equivocado. Ahora mismo, al no ser alternativas, si selecciono una tarjeta puedo añadir otras, pero no desmarcar las anteriores.

**Comment by AlvaroMartinFernandez** [comment]
YA estan los cambios realizados
- Ya esta responsive.
- solo se puede marcar un checkbox
- $ de dolar tiene estilos
- Los campos input text solo aceptan caracteres normales.

**Comment by agarzon48** [comment]
¡Perfect!
